### ISSUE TITLE
来个IP质量好的

### ISSUE THREAD

**Issue by XuanRanDev** [pigpigchacha/PigchaVPN#137]
来个IP质量好的，Linux和chatgpt使用，辣鸡机场IP不干净的别来。

**Comment by flsrdlx** [comment]
Git Issues上推荐的机场都注册了一遍，最后还是自己找的，注重性价比的看看这个吧：[Taishan](https://jpcdn.ts123.cc/register?code=U5PaaGDr)
Taishan机场是个很便宜的新机场，看域名是23年5月份开业的，目前TG群人数4900+。说是由海外团队运营，全节点解锁流媒体和ChatGPT，有中转和IPLC专线。价格很能打，个人觉得有两档套餐的价格都很不错。

【划重点:可以按月付 ￥8.5/64GB 年付最低￥7/128GB/月】

最低档一个月￥8.5/64GB，年付还能打个折，只要￥68，这入门门槛相比其他机场就低很多了。再一个就是￥10/128GB的套餐，年付也只要￥84，相比低档套餐，价格只多了￥24，但是流量是翻倍了，性价比属实是拉满。别人机场两三个月的钱，搁这可以用一年。但是一分钱一分货，速度、稳定性上肯定比贵的还是有不如的，如果能够接受的话，还是建议购买的。毕竟一年￥68，还要啥自行车啊。适合轻度使用或者对价格敏感的人。

**Comment by XuanRanDev** [comment]
> Git Issues上推荐的机场都注册了一遍，最后还是自己找的，注重性价比的看看这个吧：[Taishan](https://jpcdn.ts123.cc/register?code=U5PaaGDr) Taishan机场是个很便宜的新机场，看域名是23年5月份开业的，目前TG群人数4900+。说是由海外团队运营，全节点解锁流媒体和ChatGPT，有中转和IPLC专线。价格很能打，个人觉得有两档套餐的价格都很不错。
> 
> 【划重点:可以按月付 ￥8.5/64GB 年付最低￥7/128GB/月】
> 
> 最低档一个月￥8.5/64GB，年付还能打个折，只要￥68，这入门门槛相比其他机场就低很多了。再一个就是￥10/128GB的套餐，年付也只要￥84，相比低档套餐，价格只多了￥24，但是流量是翻倍了，性价比属实是拉满。别人机场两三个月的钱，搁这可以用一年。但是一分钱一分货，速度、稳定性上肯定比贵的还是有不如的，如果能够接受的话，还是建议购买的。毕竟一年￥68，还要啥自行车啊。适合轻度使用或者对价格敏感的人。

逼我拉黑你

**Comment by lizhentao6a** [comment]
> > Git Issues上推荐的机场都注册了一遍，最后还是自己找的，注重性价比的看看这个吧：[Taishan](https://jpcdn.ts123.cc/register?code=U5PaaGDr) Taishan机场是个很便宜的新机场，看域名是23年5月份开业的，目前TG群人数4900+。说是由海外团队运营，全节点解锁流媒体和ChatGPT，有中转和IPLC专线。价格很能打，个人觉得有两档套餐的价格都很不错。
> > 【划重点:可以按月付 ￥8.5/64GB 年付最低￥7/128GB/月】
> > 最低档一个月￥8.5/64GB，年付还能打个折，只要￥68，这入门门槛相比其他机场就低很多了。再一个就是￥10/128GB的套餐，年付也只要￥84，相比低档套餐，价格只多了￥24，但是流量是翻倍了，性价比属实是拉满。别人机场两三个月的钱，搁这可以用一年。但是一分钱一分货，速度、稳定性上肯定比贵的还是有不如的，如果能够接受的话，还是建议购买的。毕竟一年￥68，还要啥自行车啊。适合轻度使用或者对价格敏感的人。
> 
> 逼我拉黑你

这个人每个issue下面都有他。。。一眼广，还在那装模做样的。。

**Comment by swsunbin** [comment]
https://soonlink.net/passport/#/register?code=v8FfKZap ，这个速度很快，不限制流量，注册就送三天，可以试一试。

**Comment by ciaoyizhen** [comment]
@XuanRanDev 找到了 推我一下  目前只看到anycast支持linux  但是tmd 太贵了。。。  而且没pigcha好用。。。

**Comment by XuanRanDev** [comment]
> @XuanRanDev 找到了 推我一下  目前只看到anycast支持linux  但是tmd 太贵了。。。  而且没pigcha好用。。。

大部分IP贼拉，迫不得已我刚自己搭建了一个，速度还行，一个月3.5刀，也不是不能接受

**Comment by haiy0725** [comment]
快來下載好玩的應用程式 https://getwawapp.com/?code=T2LHX3

**Comment by yuyusmile** [comment]
这个不错linux也可以用 http://47.116.73.91:65533/index.php/#/register?code=mu6S3FrF

**Comment by IQIUM** [comment]
> > @XuanRanDev 找到了 推我一下  目前只看到anycast支持linux  但是tmd 太贵了。。。  而且没pigcha好用。。。
> 
> 大部分IP贼拉，迫不得已我刚自己搭建了一个，速度还行，一个月3.5刀，也不是不能接受

大佬能不能请教一下怎么自己搭建一个(抱拳)

**Comment by ciaoyizhen** [comment]
@XuanRanDev 怎么自己搭？ 大佬救救

**Comment by lizhentao6a** [comment]
> https://soonlink.net/passport/#/register?code=v8FfKZap ，这个速度很快，不限制流量，注册就送三天，可以试一试。

确定吗，真的用过吗，我看着网页挺高大上注册了个试试，真的难用，动不动就掉，别说是因为试用的连接不好，试用都不行谁敢去订阅。。

**Comment by Lincse** [comment]
> 来个IP质量好的，Linux和chatgpt使用，辣鸡机场IP不干净的别来。

https://store.holytech.tech/aff.php?aff=6773这个可以试试看

**Comment by C12590** [comment]
发现一个平替，朋友用了4年的。油管4K无压力。速度相当可以，还可以试用几天
https://r8tmt.wgy.life/auth/register?code=yx6K
