### ISSUE TITLE
pigcha一倒，各路牛鬼蛇神闻着味就来了。。。

### ISSUE THREAD

**Issue by lizhentao6a** [pigpigchacha/PigchaVPN#140]
issue中全是广告，或者一些发自己邀请链接搞返现的。。。。

**Comment by techyangj** [comment]
确实

**Comment by dgzn123** [comment]
服了，现在没梯子用了。。。

**Comment by Kep1er0103** [comment]
https://www.catssr.host/#/register?code=umT73J14，可以试试我这个，可以跑满千兆的，不过是以流量计的

**Comment by yuyusmile** [comment]
这个不错linux也可以用 http://47.116.73.91:65533/index.php/#/register?code=mu6S3FrF

**Comment by lizhentao6a** [comment]
> 笑死了，你这个issue下面也被广告包围了

看到了。。。。。
