### ISSUE TITLE
我不到啊，他们说这个好用我就用了

### ISSUE THREAD

**Issue by xiaocuanChina** [pigpigchacha/PigchaVPN#155]
[点我用好用的机场](https://sourl.cn/ubjaCu)

**Comment by tomener** [comment]
🚀🚀🚀好用、稳定、便宜

**推荐 👉 这个不错，可以按月、按流量**
- 按月份  3.8元/月10G，5.8元/月45G，8.8元/月95G，13.8/月210G，25.8/月480G
- 按流量  9.8元20G不限时永久有效，19.8元100G，38元260G

[稳定VPN](http://b.m0w.cn/3FalsO)
