### ISSUE TITLE
网址应该可以打开了，点击site2，但是弹出的是不好的消息😭

### ISSUE THREAD

**Issue by PreX-AW** [pigpigchacha/PigchaVPN#183]
.

**Comment by PreX-AW** [comment]
![image](https://github.com/user-attachments/assets/42c6adb8-9c19-4512-ade6-ffbf5faa22b9)

**Comment by Wyt-Lab** [comment]
看看这个吧 https://github.com/pigpigchacha/PigchaVPN/issues/200#issuecomment-2359927852
