### ISSUE TITLE
免费的不能代理git？

### ISSUE THREAD

**Issue by InuYasha000** [pigpigchacha/PigchaVPN#2]
免费的500M流量不能代理github吗？我使用免费的流量并没有加速效果

**Comment by pigpigchacha** [comment]
> 免费的500M流量不能代理github吗？我使用免费的流量并没有加速效果

可以代理！git地址要是https哦，并勾选git代理！

**Comment by pigpigchacha** [comment]
> 免费的500M流量不能代理github吗？我使用免费的流量并没有加速效果

最新版是默认加速git
