### ISSUE TITLE
@pigcha技术

### ISSUE THREAD

**Issue by alexander2h** [pigpigchacha/PigchaVPN#200]
因为tg群无法发消息，只能在这里给你留言了。想问下你是之前老tg群里一直在线发表情那人吗？🤓

还有就是传言严某被开盒，他就是pigcha老板？还是说只是代收款公司的老板？老板被逮捕这么惨吗

**Comment by Wyt-Lab** [comment]
最近冒出了一个官方技术，而且搞了一系列操作。从消息处得到的是作者被抓.。目前有几个疑点
1.github账号一般来说是作者或者信任的人在管理，作者被抓那么附带的是技术可能也会进去这时候不可能冒头修改github来继续引流到新的tg频道？
2.TG频道搞了一个先复活哪个客户端的投票，身为技术那么相关的客户端源代码应该是在手上的才对？为何还要再搞个投票？
3. https://github.com/pigpigchacha/officialsite/commits?author=pigpigchacha 从提交记录来看账号是处于一个活跃的状态，帽子叔叔就算拿到相关账号的情况下是不会动账号的里面的任何东西，只会从里面找寻他们想要的一些蛛丝马迹。
4.新的频道中说服务器、域名、社交账号等已被控制，所以这时候就能结合我前面的第三点和第一点，这个技术如何敢或者说做到去修改官网的服务器以及github，除非.....
5.从新TG频道推送的新消息中有一句话说是他们会继承pigcha所有优点而为何不是说将会尽快恢复呢？，那么我们继续结合前面的 2  4 点 仔细想想？
我有以下几个猜测：
1.作者没进去，去其他机场等场所放消息说自己被抓 实则承担不起服务器高昂的费用选择了跑路后续想换壳再来。
2.作者被同行控制住了，想借此将用户引流到自己的产品上（有点不切实际，但一切皆有可能）
3.作者进去了，作者购买的服务器商拥有服务器的权限擅自更改了主页，因为你没发现弹出的公告信息基本都是服务器IP地址的官网，并非 https://pigpigchacha.github.io/officialsite 官网
4.我从 https://github.com/pigpigchacha/officialsite/commit/3d120f7274e39d8298ad7d4727f82317c90671bb#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R20 中提交的内容将base64编码的js代码解码出来看他的弹窗消息是网站已下线
![image](https://github.com/user-attachments/assets/a2958c89-b76b-47ee-bff5-b98f0541e11f)
以上是9.18号更改的，我们看看前面8.8号提交的
![image](https://github.com/user-attachments/assets/99b408c4-e204-4381-b7b5-c613dc41ee24)
上图是8.8提交的内容是没有任何弹窗，所以根据这些信息可以对应我前面第3点的猜想。

仁者见仁智者见智吧。

**Comment by cjcego** [comment]
![微信截图_20240919133736](https://github.com/user-attachments/assets/220cd558-c4f4-44c6-af76-ae43bbeea843)

**Comment by Wyt-Lab** [comment]
> 这是订阅群里刚发的；大家可以看下； ![微信截图_20240919133736](https://private-user-images.githubusercontent.com/64342316/368854639-220cd558-c4f4-44c6-af76-ae43bbeea843.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MjQ4NDcsIm5iZiI6MTcyNjcyNDU0NywicGF0aCI6Ii82NDM0MjMxNi8zNjg4NTQ2MzktMjIwY2Q1NTgtYzRmNC00NGM2LWFmNzYtYWU0M2JiZWVhODQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA1NDIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMzkyODdhNzI1ZDExOWQ3ZmZiNjcxM2U1MzRjMTlhMTk1NjM0YzY2OTU4MTYzNGY1NTVlNmM3NmFlOTkwZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3VmEcR_WJhvsvJu6s3sV4u-MHDNGdbqjaAR-Wdl3m68)

根据他的说法我们首先从几个回答来判断目前Pigcha最终结果以及这个技术是真假技术。
1.所谓技术回答说github账号是作者个人账号，所以可以确认的是目前github中 https://github.com/pigpigchacha?tab=repositories 下的所有项目只有officialsite是昨天进行了一次修改，所以目前可以判断要么作者要么帽子叔叔。

2.所谓技术回答说客户端运行成本很高，那么我们姑且暂时相信他有客户端源码，接下来要知道的是实际上做过开发和运营的都知道除了apple之外其他的客户端运营成本基本可以忽略不计，因为有客户端源码在情况下特别是安卓那么他就已经做好了各种机型的兼容.剩下的就是修改下会员系统的api以及相关节点的连接服务信息，所以有点说不过去，居然拥有客户端的源码情况下剩下的就是会员后端、流量监控等源码，那么居然有客户端源码的情况下按理来说后端源码应该是会有的。

3.所谓技术回答说不用修改服务器IP在他那里，首先我们从灰产的角度分析一个事情就是作者不可能用自己的真实实名信息去腾讯云上购买服务器，所以有可能他并非技术而是作者在他手上购买了黑服务器，所以服务器IP在他那

4.所谓技术回答说1:1搭建需要高昂的费用，他只是个技术没那么大的财力。那么问题来了居然没有那么大财力他怎么能做到他之前所说继承Pigcha所有优点呢？

5.所谓技术还在频道说可以用pigcha.com域名的ssl证书以及DNS解析权来证明他是技术，在这里可以看我第3点所说，Pigcha是一个非法的业务，所以作者在这个所谓的技术手上购买服务器以及域名不足为奇，那么这个所谓的技术到底是真技术还是假技术我们不得而知。

各位可以综合以上几点自行判断，我也是做技术开发的。很多东西我也懂只是搞VPN是犯法的。

**Comment by AlvinTorres4** [comment]
因为pigcha用不了，就里看issues里推荐的VPN注册购买服务，试了一圈下了，很多是用不了ChatGPT，而且速度还特别慢，看个视频都要卡很多次，真的是一分钱一分货。

说说我目前使用下来值得使用的，也算是给需要VPN的同学踩踩雷了。

先说万城VPN，可以正常使用ChatGPT，节点丰富，速度快，关键是它家对自己的服务足够自信，注册就送1小时体验包，不满意可以不订阅。 [万城官网链接](https://user.vcsite02.com/#/sign-up?code=0BnXRJud)

接下来要说的是WgetCloud，价格略贵，但服务稳定速度快，也能正常使用ChatGPT，支持流媒体，新用户有85折优惠，不想折腾首选，[WgetCloud官网链接](https://invite.wgetcloud.ltd/auth/register?code=jll8)

**Comment by xiaozhuxiong991026** [comment]
之前pigcha用完了2年，续了第二个2年用了半年 除了这种事情，对我来说 很简单，能恢复之前的账号和时长，就试试。不能的话，就换别的机场就好了

**Comment by cjcego** [comment]
到时候能给我恢复就行，我这也是充的年费！而且做任务推广加的那些不知道能不能恢复呢！

**Comment by alexander2h** [comment]
但是到底是不是真的也无所谓，只要能做到pigcha原先水平对我来说就ok了。况且人家也说了提供购买收据截图能够恢复之前的时长，这点也很有诚意了。anyway，我在意的是能不能达到之前的服务水平，加之我还有一年多的订阅，如果这位技术继续经营的好以后继续续费也完全没问题，担心圈钱的就按月买呗。

**Comment by codepgq** [comment]
对了，只要能恢复到之前的服务水平，我管你谁谁开的，好用稳定才是核心需求

> 但是到底是不是真的也无所谓，只要能做到pigcha原先水平对我来说就ok了。况且人家也说了提供购买收据截图能够恢复之前的时长，这点也很有诚意了。anyway，我在意的是能不能达到之前的服务水平，加之我还有一年多的订阅，如果这位技术继续经营的好以后继续续费也完全没问题，担心圈钱的就按月买呗。

**Comment by aha-dlut** [comment]
> 但是到底是不是真的也无所谓，只要能做到pigcha原先水平对我来说就ok了。况且人家也说了提供购买收据截图能够恢复之前的时长，这点也很有诚意了。anyway，我在意的是能不能达到之前的服务水平，加之我还有一年多的订阅，如果这位技术继续经营的好以后继续续费也完全没问题，担心圈钱的就按月买呗。

支持

**Comment by masalaempire** [comment]
> 这是订阅群里刚发的；大家可以看下； ![微信截图_20240919133736](https://private-user-images.githubusercontent.com/64342316/368854639-220cd558-c4f4-44c6-af76-ae43bbeea843.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3Mzc5MjYsIm5iZiI6MTcyNjczNzYyNiwicGF0aCI6Ii82NDM0MjMxNi8zNjg4NTQ2MzktMjIwY2Q1NTgtYzRmNC00NGM2LWFmNzYtYWU0M2JiZWVhODQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA5MjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYzQ4OWZkNmFhMDYzY2Q1ZjdiNDZmZWRiMzg2YzFlOTllNWU5NDU4Y2VlNDIwODA5NDdhOTUwOTczMjQ5NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XK3BDtGjePIDheHiQxd4K6b9y-MlbGtUO0TbE-lEIRc)

感觉回答的模棱两可，不像真的。

**Comment by tczy183** [comment]
真是屁事多，人家愿意给你搞，还在叨叨

**Comment by Wyt-Lab** [comment]
> > 这是订阅群里刚发的；大家可以看下；![微信截图_20240919133736](https://private-user-images.githubusercontent.com/64342316/368854639-220cd558-c4f4-44c6-af76-ae43bbeea843.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3Mzc5MjYsIm5iZiI6MTcyNjczNzYyNiwicGF0aCI6Ii82NDM0MjMxNi8zNjg4NTQ2MzktMjIwY2Q1NTgtYzRmNC00NGM2LWFmNzYtYWU0M2JiZWVhODQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA5MjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYzQ4OWZkNmFhMDYzY2Q1ZjdiNDZmZWRiMzg2YzFlOTllNWU5NDU4Y2VlNDIwODA5NDdhOTUwOTczMjQ5NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XK3BDtGjePIDheHiQxd4K6b9y-MlbGtUO0TbE-lEIRc)
> 
> 回答感觉的模块两可，不是真的。

新频道还一直推说我有广告诡计，身为技术用新号在issues扯东扯西，哪个人不有千百身份？网络上的身份都是自己给的。那位所谓的技术要推翻我说的这些就得实打实拿出东西来，这么简单的答辩。而且从Pigcha无法使用已经过去半个月了他突然冒泡出来...所以很多时候都要考虑对方是不是还想把某些羊再割一遍，加上这几年网上骗子五花八门的。

**Comment by Wyt-Lab** [comment]
> 也不是真的也无所谓，到底能实现pigcha认知对我来说就ok了。条件且人家也只好提供购买收据截图能够恢复之前的时长，这也有诚意了。不管怎样，我意思是不能达到之前的服务水平，加之我还有一年多的订阅，如果这个技术继续经营的好以后继续续费也完全没问题，担心圈钱的就按月买呗。

这也是单纯好心的提醒下而已，至于其他的也是一群羊的事了。多的不说，少的也不说。总之一个两次提起成本大的技术要复活Pigcha或继承Pigcha优点，就这一点上都质的怀疑！毕竟这网络上有点疑心病是好的。

**Comment by Wyt-Lab** [comment]
> 之前pigcha用完了2年，续了第二个2年用了半年生长了这种事情，对我来说很简单，能恢复之前的账号和时长，就试试。不能的话，就换其他机场就好了

自己有能力就自己搭建就行了，买别人的机场用着闹心。

**Comment by alexander2h** [comment]
> > 也不是真的也无所谓，到底能实现pigcha认知对我来说就ok了。条件且人家也只好提供购买收据截图能够恢复之前的时长，这也有诚意了。不管怎样，我意思是不能达到之前的服务水平，加之我还有一年多的订阅，如果这个技术继续经营的好以后继续续费也完全没问题，担心圈钱的就按月买呗。
> 
> 
> 
> 这也是单纯好心的提醒下而已，至于其他的也是一群羊的事了。多的不说，少的也不说。总之一个两次提起成本大的技术要复活Pigcha或继承Pigcha优点，就这一点上都质的怀疑！毕竟这网络上有点疑心病是好的。

嗯，你如果不是友商，明白你的好意。但各位想必也是会自己观察，会找pigcha的人就是图方便，自己搭建简单，但总归是花时间，而且线路、带宽并不能做到和以前的pigcha一样。就算你选择其他机场你也不知道他们什么时候跑路，做这行的除非国外正规公司，跑路只是时间问题。因此也不必费心去分析那么多了，希望技术能好好做，这本来就是一个你情我愿的事情

**Comment by xiaozhuxiong991026** [comment]
> > 之前pigcha用完了2年，续了第二个2年用了半年生长了这种事情，对我来说很简单，能恢复之前的账号和时长，就试试。不能的话，就换其他机场就好了
> 
> 自己有能力就自己搭建就行了，买别人的机场用着闹心。

自己搭过，垃圾服务器网速不行，好服务器价格不如机场实惠

**Comment by cookingBird** [comment]
我之前冲勒200G流量，还有170多个G没用，SM奸商

**Comment by cx2091076038** [comment]
> 之前pigcha用完了2年，续了第二个2年用了半年 出了这种事情，对我来说 很简单，能恢复之前的账号和时长，就试试。不能的话，就换别的机场就好了

换别的吧，打着pigcha的名义出来圈钱的

**Comment by cx2091076038** [comment]
> 我之前冲勒200G流量，还有170多个G没用，SM奸商

换别的吧，打着pigcha的名义出来圈钱的
