### ISSUE TITLE
为啥现在得开着加速才能访问网络

### ISSUE THREAD

**Issue by qq1456680570** [pigpigchacha/PigchaVPN#25]
关掉加速反而不能正常上网了，必须得开着加速才行，有检查过系统的代理也有关掉过，但是不开软件加速就是访问不了正常网站，比如百度之类的

**Comment by liu7A** [comment]
个人建议：在关闭加速器或关机前先断开连接。 官网推荐安装一个浏览器插件，那个插件也挺好用的，可以在浏览器配置直接连接还是代理链接，像你这种情况直接在插件里手动切换为直接连接就行。

**Comment by pigpigchacha** [comment]
> 个人建议：在关闭加速器或关机前先断开连接。 官网推荐安装一个浏览器插件，那个插件也挺好用的，可以在浏览器配置直接连接还是代理链接，像你这种情况直接在插件里手动切换为直接连接就行。

正解
