### ISSUE TITLE
Bug report: 现停止加速后，无法打开网页

### ISSUE THREAD

**Issue by b-niu** [pigpigchacha/PigchaVPN#27]
自2023年1月中旬以来，pigcha出现此问题。打开加速可以访问网页，停止加速无法访问网页。

netsh winsock reset、重置网络均尝试过，共试用了四五种方法，无一成功

**Comment by pigpigchacha** [comment]
> 

首先 第一检查下浏览器代理，是否指向了pigcha的代理地址，如果有，请设置为系统代理
其次 你可以尝试下设置电脑系统的dns为114.114.114.114
