### ISSUE TITLE
Git 代理报443

### ISSUE THREAD

**Issue by modakai** [pigpigchacha/PigchaVPN#37]
![image](https://github.com/pigpigchacha/PigchaVPN/assets/124060255/e67e4c58-7dd2-43d4-92a9-8e0a0a5f39a9)
开了Git 代理后，GIt push到 GitHub 时 报 443 错误
![image](https://github.com/pigpigchacha/PigchaVPN/assets/124060255/1f20843c-2c83-4fd2-8879-3ed8f0ef2f01)
这怎么解决

**Comment by pigpigchacha** [comment]
那可能是 你本地存在多份git安装包！
