### ISSUE TITLE
windows版在15.6寸的屏幕下的窗口太太太小了 😢 

### ISSUE THREAD

**Issue by voidzlfan** [pigpigchacha/PigchaVPN#4]
软件很好用，不需要什么操作
但是字体巨小，验证码看不清楚，而且还不能放大，希望可以改进下

**Comment by pigpigchacha** [comment]
> 软件很好用，不需要什么操作
> 但是字体巨小，验证码看不清楚，而且还不能放大，希望可以改进下

使用最新版试试呢，已经支持了DPI缩放，窗口也可放大缩小
