### ISSUE TITLE
挂一会之后，导致mac异常关机，很严重啊。

### ISSUE THREAD

**Issue by Numen-fan** [pigpigchacha/PigchaVPN#7]
panic(cpu 5 caller 0xffffff800331264a): "Invalid waitq: 0"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.81.3/osfmk/kern/waitq.c:5581
Backtrace (CPU 5), Frame : Return Address
0xffffffa056e3b850 : 0xffffff80032bab4d 
0xffffffa056e3b8a0 : 0xffffff80033fd7e3 
0xffffffa056e3b8e0 : 0xffffff80033ede1a 
0xffffffa056e3b930 : 0xffffff800325fa2f 
0xffffffa056e3b950 : 0xffffff80032ba3ed 
0xffffffa056e3ba70 : 0xffffff80032ba6d8 
0xffffffa056e3bae0 : 0xffffff8003abef9a 
0xffffffa056e3bb50 : 0xffffff800331264a 
0xffffffa056e3bb90 : 0xffffff800381818c 
0xffffffa056e3bc20 : 0xffffff800381ec4f 
0xffffffa056e3bc60 : 0xffffff8003830ad1 
0xffffffa056e3bdd0 : 0xffffff8003838f8e 
0xffffffa056e3be50 : 0xffffff800383a1d9 
0xffffffa056e3bef0 : 0xffffff8003839fb9 
0xffffffa056e3bf40 : 0xffffff80039698cb 
0xffffffa056e3bfa0 : 0xffffff80032601f6 

Process name corresponding to current thread: PigchaProxy

Mac OS version:
20D74

Kernel version:
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Kernel UUID: C86236B2-4976-3542-80CA-74A6B8B4BA03
KernelCache slide: 0x0000000003000000
KernelCache base:  0xffffff8003200000
Kernel slide:      0x0000000003010000
Kernel text base:  0xffffff8003210000
__HIB  text base: 0xffffff8003100000
System model name: MacBookPro15,4 (Mac-53FDB3D8DB8CA971)
System shutdown begun: NO
Hibernation exit count: 0

System uptime in nanoseconds: 3494717960788
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000032dad6c3622
  Sleep   : 0x0000009be5a166a5 0x00000001ac2cf93e 0x0000000000000000
  Wake    : 0x0000009bf2854597 0x000000f26b3f5338 0x0000009bf1161dbb
last started kext at 670692475279: >!UAudio	401.4 (addr 0xffffff7fa3710000, size 307200)
loaded kexts:
>!APlatformEnabler	2.7.0d0
>AGPM	119
>X86PlatformShim	1.0.0
>!ATopCaseHIDEventDriver	4030.5
>!AHIDALSService	1
@filesystems.autofs	3.0
@fileutil	20.036.15
>!AGraphicsDevicePolicy	6.2.2
@AGDCPluginDisplayMetrics	6.2.2
>pmtelemetry	1
>LuaHardwareAccess	1.0.16
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
>!AUpstreamUserClient	3.6.8
|IO!BSerialManager	8.0.3d9
>!A!IKBLGraphics	16.0.1
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!ADiskImages2	1
>BridgeAudioCommunication	100.2
>!AAVEBridge	6.1
>!ABridgeAudio!C	100.2
>!AFIVRDriver	4.1.0
>AGDCBacklightControl	6.2.2
>!ABacklight	180.3
>!AThunderboltIP	4.0.3
>!AGFXHDA	100.1.431
>ACPI_SMC_PlatformPlugin	1.0.0
>!AMCCSControl	1.14
>!A!IPCHPMC	2.0.1
>!A!ICFLGraphicsFramebuffer	16.0.1
>!A!ISlowAdaptiveClocking	4.0.0
@filesystems.apfs	1677.81.1
>BCMWLANFirmware4378.Hashstore	1
>BCMWLANFirmware4377.Hashstore	1
>BCMWLANFirmware4364.Hashstore	1
>BCMWLANFirmware4355.Hashstore	1
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.60.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!A!BModule	1
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!ABCMWLANBusInterfacePCIeMac	1
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	310
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
>!UAudio	401.4
>!AHIDKeyboard	223
>!AHS!BDriver	4030.5
>IO!BHIDDriver	8.0.3d9
>!AActuatorDriver	4400.28
>!AMultitouchDriver	4400.28
>!AInputDeviceSupport	4400.35
@kext.triggers	1.0
>!AGraphicsControl	6.2.2
|IOAVB!F	930.1
@!AGPUWrangler	6.2.2
@plugin.IOgPTPPlugin	900.11
|IOEthernetAVB!C	1.1.0
>!ASMBusPCI	1.0.14d1
>!ABacklightExpert	1.1.0
>!AThunderboltEDMSink	5.0.3
>!AThunderboltDPOutAdapter	8.1.4
>!AHDA!C	283.15
|IOHDA!F	283.15
|IONDRVSupport	585
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>!ASMBus!C	1.0.18d1
>IOPlatformPlugin!F	6.0.0d8
|IOAccelerator!F2	439.52
@!AGraphicsDeviceControl	6.2.2
|IOGraphics!F	585
|IOSlowAdaptiveClocking!F	1.0.0
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc.ncm	5.0.0
>usb.cdc.ecm	5.0.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!AXsanScheme	3
>usb.!UVHCIBCE	1.2
>usb.!UVHCICommonBCE	1.0
>usb.!UVHCI	1.2
>usb.!UVHCICommon	1.0
>!AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
>!AThunderboltPCIDownAdapter	4.1.1
>!AThunderboltDPInAdapter	8.1.4
>!AThunderboltDPAdapter!F	8.1.4
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!A!ILpssDmac	3.0.60
>!AThunderboltNHI	7.2.8
|IOThunderbolt!F	9.3.2
>!ABSDKextStarter	3
|IOSurface	289.3
@filesystems.hfs.encodings.kext	1
>IO!BHost!CPCIeTransport	8.0.3d9
|IO!BHost!CTransport	8.0.3d9
>!AConvergedIPCOLYBTControl	1
>!AConvergedPCI	1
>!A!BDebug	1
>!A!BDebugService	1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!A!ILpssI2C	3.0.60
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!ABCMWLANCoreMac	1.0.0
|IOSerial!F	11
|IO80211!FV2	1200.12.2b1
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
>IOImageLoader	1.0.0
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
>!AMultiFunctionManagerMac	1
>corecapture	1.0.4
>!ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOTimeSync!F	900.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.3d9
|IOReport!F	47
|IO!BPacketLogger	8.0.3d9
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.60.2
|IOUSBMass!SDriver	184.40.6
|IOSCSIBlockCommandsDevice	436.40.6
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.40.6
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1

**Comment by Crysking** [comment]
遇到了同样的问题，怎么设置都解决不了，请问您解决这个问题了吗？谢谢

**Comment by pigpigchacha** [comment]
下载最新版本，运行下
