### ISSUE TITLE
有人联系上了吗？贴个图

### ISSUE THREAD

**Issue by alexander2h** [pigpigchacha/PigchaVPN#98]
如题

**Comment by ShaoClean** [comment]
![image](https://github.com/user-attachments/assets/82a6a76f-1c5f-42e0-a8f7-db308fc3fc50)
不知道是真是假

**Comment by zechzdelta** [comment]
> ![image](https://private-user-images.githubusercontent.com/98806795/364678714-82a6a76f-1c5f-42e0-a8f7-db308fc3fc50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzM1OTAsIm5iZiI6MTcyNTUzMzI5MCwicGF0aCI6Ii85ODgwNjc5NS8zNjQ2Nzg3MTQtODJhNmE3NmYtMWM1Zi00MmUwLWE4ZjctZGIzMDhmYzNmYzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEwNDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4OTljOWNhMzY2NzUyNzg3NDJkNmEzMjI3NmE5ZmE2N2YzMzNhMjRlMWNjODVkNjczYTVlMDdlZjE3MGM2ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vaw0pFpkg3gGtJcRgH3le9B9iYyw1ahY-BC7EIaSpN4) 不知道是真是假

之前一般是节点被攻击，公告都是软件发的，要是软件被攻击发不了公告预案不完善也正常，官网好像也不发公告，希望人没事吧，挂梯子这么些年头回见打软件的，再等等看

**Comment by huazhaochen01** [comment]
纯靠一张嘴瞎说，你们不会以为作者不会上网吧？git不能上?电报能上吧？??电报不能上微信总能上了吧？远程协助的那个客服微信也联系不上。即便是电报被封了，创个小号加进来发个公告不难吧？？发出消息的途径多的是
